# Generated by Django 4.2.7 on 2024-10-01 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='contestant_images/')),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('votes', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('contestant_id', models.CharField(editable=False, max_length=20, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voters_id', models.CharField(blank=True, max_length=13, null=True)),
                ('first_name', models.CharField(blank=True, max_length=13, null=True)),
                ('last_name', models.CharField(blank=True, max_length=13, null=True)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('matricnum', models.CharField(blank=True, max_length=200, null=True)),
                ('department', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.contestant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.user_data')),
            ],
        ),
        migrations.AddField(
            model_name='user_data',
            name='voted',
            field=models.ManyToManyField(blank=True, through='vote.UserVote', to='vote.contestant'),
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('no_of_hours', models.PositiveIntegerField(editable=False)),
                ('is_ended', models.BooleanField(default=False)),
                ('winners', models.JSONField(blank=True, default=dict, null=True)),
                ('contestants', models.ManyToManyField(to='vote.contestant')),
                ('position', models.ManyToManyField(null=True, to='vote.position')),
            ],
        ),
        migrations.AddField(
            model_name='contestant',
            name='position',
            field=models.ManyToManyField(null=True, to='vote.position'),
        ),
    ]
