# Generated by Django 4.2.7 on 2024-10-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_remove_contestant_position_contestant_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='current_time',
            field=models.DateTimeField(null=True),
        ),
    ]
