# Generated by Django 4.2.7 on 2024-10-09 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_election_current_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='current_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
