# Generated by Django 4.2.7 on 2024-11-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_alter_election_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
